### PR TITLE
misc clean up and fixes

### PR DESCRIPTION
**Pull request by gboeing**
@shiqin-liu at some point in your transition to the new Docker repo, the `FROM` command was changed from `continuumio/miniconda3` to my old personal repo. If we're transferring the image from a personal account to an org account, we don't want it to depend on that old personal account. This PR changes the `FROM` back to its old value, corrects the line endings (which seem to have been saved as [Windows-style](https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings)), and performs a few other misc clean-ups. cc @carlhiggs.

### CODE REVIEW

**Comment by gboeing** [comment]
In d6ebca0 I pinned the key dependency versions in `requirements.txt` to the minor versions that we had in the Docker image at the start of this year. Version pinning will allow a consistent environment even if the image needs to be rebuilt for some reason.

**Comment by shiqin-liu** [comment]
> @shiqin-liu at some point in your transition to the new Docker repo, the `FROM` command was changed from `continuumio/miniconda3` to my old personal repo. If we're transferring the image from a personal account to an org account, we don't want it to depend on that old personal account. This PR changes the `FROM` back to its old value, corrects the line endings (which seem to have been saved as [Windows-style](https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings)), and performs a few other misc clean-ups. cc @carlhiggs.

Thanks Geoff! I was experiencing some versioning issues at the beginning when rebuilding the image, so I tried with the personal repo and see if I can get the correct dependency... Thanks for correcting that and the `requirements.txt`.

**Comment by gboeing** [comment]
I just pushed all the images/tags from the old personal account to the new team [Docker Hub](https://hub.docker.com/r/globalhealthyliveablecities/global-indicators/tags) (this over-wrote the newly rebuilt image that @shiqin-liu had pushed to the team account yesterday). So now it is exactly the same as the old personal account. The command looked like this:

```bash
docker pull gboeing/global-indicators:latest | docker tag gboeing/global-indicators:latest globalhealthyliveablecities/global-indicators:latest | docker push globalhealthyliveablecities/global-indicators:latest
docker pull gboeing/global-indicators:20201103 | docker tag gboeing/global-indicators:20201103 globalhealthyliveablecities/global-indicators:20201103 | docker push globalhealthyliveablecities/global-indicators:20201103
docker pull gboeing/global-indicators:20200612 | docker tag gboeing/global-indicators:20200612 globalhealthyliveablecities/global-indicators:20200612 | docker push globalhealthyliveablecities/global-indicators:20200612
docker pull gboeing/global-indicators:20200123 | docker tag gboeing/global-indicators:20200123 globalhealthyliveablecities/global-indicators:20200123 | docker push globalhealthyliveablecities/global-indicators:20200123
docker pull gboeing/global-indicators:20200318 | docker tag gboeing/global-indicators:20200318 globalhealthyliveablecities/global-indicators:20200318 | docker push globalhealthyliveablecities/global-indicators:20200318
```

**Comment by gboeing** [comment]
@shiqin-liu ok, so now the new team account should be an exact replica of the images on the old personal account. When this PR is merged, I will delete the old personal repository. First, can you `docker pull globalhealthyliveablecities/global-indicators:latest`, run the indicators, and make sure we're getting the same results as before? Once you've confirmed that the image gives us reproducible analytics results, we can merge.

**Comment by shiqin-liu** [comment]
> @shiqin-liu ok, so now the new team account should be an exact replica of the images on the old personal account. When this PR is merged, I will delete the old personal repository. First, can you `docker pull globalhealthyliveablecities/global-indicators:latest`, run the indicators, and make sure we're getting the same results as before? Once you've confirmed that the image gives us reproducible analytics results, we can merge.

Sure, running now, it should take sometimes, I will confirmed once done.

**Comment by shiqin-liu** [comment]
I just finished running the indicators (my computer crash in the middle during the first run, so it took longer than expected), but all good now. I can confirm that the resulting indicators are exactly the same as before. This should be good to merge

**Review by shiqin-liu — APPROVED** [review]

**Comment by carlhiggs** [comment]
Hi @shiqin-liu and @gboeing , I just received a warning for a security vulnerability possibly related to this code update (Pillow is set to be 7.1.* in most recent update, but there's a vulnerability so it should be 8.1.1, or greater than this, apparently).   

I just lodged an issue here https://github.com/global-healthy-liveable-cities/global-indicators/issues/116 , but it only occured to me after the fact to '@' you both (so wasn't sure if you'd get the message in the edited version), and that I could respond here.  

So responding here just in case!  I've drafted a fix, but just double checking that you are okay for me to push it up to Github/DockerHub.

**Comment by carlhiggs** [comment]
And apologies --- i just realised I made these changes directly to 'main' instead of the new branch i created... That wasn't my intention, but they have been pushed up now.  I'll leave things until I expect you are both back on board tomorrow! (I won't push it up to DockerHub until we've discussed)

**Pull request merged**
