### PR TITLE
Ground-truthing Selector

### PR DESCRIPTION
**Pull request by nicholas-david**
Selector for random destinations from each quintile. 0.SetUP is a where the code is being built up. Adelaide is the only city being used for this code. 1.CreateExcel is where the code becomes iterative for all cities.

### CODE REVIEW

**Comment by nicholas-david** [comment]
@gboeing The code works and I am able to sort through the quintlied destinations all right. The only issue is that the CSV that is processed only gives destinations for Vic (the last city). Do you know what is wrong?

**Comment by gboeing** [comment]
It looks like within each city loop, you set `filenames = {}` which overwrites any prior city's results.

**Comment by nicholas-david** [comment]
@gboeing @DRosasMoctezuma 
The code is almost there, but not every city is returning 50 destinations in the final excel. I looked into this, and every city, when printed individually, does sample 50 destinations. So, what I think is happening, is that if a similar index occurs between two cities, the row gets rewritten. For example, if a destination from Olomouc has an index of 150, and then Vic has a destination with an index of 150, the Olomouc destination will get overwritten with Vic's destination info. In the end, the excel does not add a row for that destination, and we end up with too few sampled destinations in the final excel. Not totally sure how to fix this though, any ideas?

**Comment by nicholas-david** [comment]
Right now, I set the index to the OSM_ID, hoping that they are unique. I will let you know if it works once the code is done running.

**Comment by gboeing** [comment]
You could reset the index to get unique values, or create a multi-index of city+id.

**Comment by nicholas-david** [comment]
should be all finished, sending to mark and david now

**Pull request merged**
