### PR TITLE
Paring Down Data

### PR DESCRIPTION
**Pull request by nicholas-david**
This is the work I have done so far. I will continue with it unless @gboeing would rather just take a pass on the code himself.

### CODE REVIEW

**Comment by nicholas-david** [comment]
@gboeing 
At the moment, the only way I can see to pair down the code is

`df.loc[df['COLUMN_NAME'].isin(['COLUMN_VALUE1','COLUMN_VALUE2'])`

To make that work, I would have config file have
Column Name = abc
Column Values = {value1, value2)

Is there a better way?

**Comment by gboeing** [comment]
If that works, let's do it like that for now. I can spend some time thinking about it during a future revision.

**Comment by nicholas-david** [comment]
@gboeing I am at a sticking point right now. When I do it like that, all of the data is removed.

I am not sure what to do about that.

**Comment by gboeing** [comment]
should i merge it in and take a look myself?

**Comment by nicholas-david** [comment]
If you are able to that would be helpful. Thank you!

**Pull request merged**
