### PR TITLE
Addressing linux-related issues and simplifying instructions display 

### PR DESCRIPTION
**Pull request by carlhiggs**
As per #256 , there were some permissions related issues when attempting to run the software on Linux.

Using the excellently detailed issue write up by @benizar as a starting point, I developed the changes in this commit that i have tested now without issue running on Windows and Ubuntu computers (with details to be posted below).

Changes:
- instead of display instructions from echo commands within instructions.sh (which causes permissions issues as an executable file in some Linux environments), these same instructions are instead stored in an environment variable and echo-ed in the start up command
- UID and GID are defined as empty string environment variables and set to define a user in the docker compose file, which (suprisingly to me) avoids permissions issues while avoiding warning that the UID and GID were not set (occurs if they aren't already set as blank; Docker does this otherwise and sets them)
- to do the above, there is a new .env file in the project root folder containing the new environment variables: INSTRUCTIONS, UID and GID
- updated readme.md in process folder to advise that Linux users may need to run 'bash ./global-indicators.sh' prefixed by 'sudo' (as per [Docker advice on Linux post-installation](https://docs.docker.com/engine/install/linux-postinstall/))

I have successfully run the above on the following two systems without issue/warning/error to configure, analyse and generate resources for the provided example city of Las Palmas:
- Ubuntu 20.04.4 LTS
  - Processor: Intel Xeon W-2145 CPU @ 3.70GHz x 16
  - RAM: 62.5GiB  
  - Analysis step took about 0.5 minute (according to time print out from analysis)
- Windows 11 Pro for Workstations 10.0.22624 
  - Processor: Intel(R) Xeon(R) E-2236 CPU @ 3.40GHz, 3408 Mhz, 6 Core(s), 12 Logical Processor(s)
  - RAM: 32 GB
  - Analysis step took about 1 minute (according to time print out from analysis)
  - I also repeated the analysis using Windows Subsystem for Linux on the same computer (didn't require sudo)

It would be great if some MacOS users could test this out; thanks!

### CODE REVIEW

**Comment by carlhiggs** [comment]
ps.  I've added a few people as reviewers to cast the net widely as I know everyone is busy --- hopefully someone can look at this sooner than later and set it to run to confirm it works on
- someone else's MacOS computer (priority; not tested)
- someone else's Ubuntu computer
- someone else's Windows computer

I think once we have confirmed this works on each of these platforms when not run by me, it should be good to merge (ie. don't need to have all reviewers review - but if people can, so we can get this sorted sooner than later, I'd appreciate it!).

Perhaps we could consider having this as a merge rule in future (run on 3x platforms, by persons other than the pull requester).

**Comment by gboeing** [comment]
> Perhaps we could consider having this as a merge rule in future (run on 3x platforms, by persons other than the pull requester).

We really should just set up a simple CI for any PRs or pushes to `main` to run the script on windows, mac, linux on github actions.

**Comment by benizar** [comment]
That was a fast!!

I just cloned and tested the `linux` branch and everything worked perfectly with the example data (approximately took 3.1 minutes, but I think it was faster than that). I'm in a different Ubuntu 22.04, with the latest docker installation.

The `.env`file is much more elegant that the fast-and-dirty patch I proposed XD

I'm afraid I don't have access to a Win or iOS computer but I think that these commits should not affect any other system. On Monday, we will test it on windows just to be sure.

**Comment by gboeing** [comment]
> We really should just set up a simple CI for any PRs or pushes to `main` to run the script on windows, mac, linux on github actions.

@carlhiggs here's a simple example to copy from if you agree: https://github.com/gboeing/osmnx/blob/main/.github/workflows/tests.yml

**Comment by carlhiggs** [comment]
@gboeing sounds like an ideal solution; thank you for sharing the example workflow!  I could try to look at this later today or tomorrow, but happy if you want/had time to set that up.  Thanks all!

**Comment by carlhiggs** [comment]
> > We really should just set up a simple CI for any PRs or pushes to `main` to run the script on windows, mac, linux on github actions.
> 
> @carlhiggs here's a simple example to copy from if you agree: https://github.com/gboeing/osmnx/blob/main/.github/workflows/tests.yml

I just had a look at the example, and thinking about our use case with the way things currently work (software to be run/tested using a docker compose environment with ghsci and postgis containers), I'm not immediately sure how/if it's possible to do this exactly using the GitHub actions approach.  Any thoughts/experience?

Bundling our software within the docker image itself would be another approach (e.g. like you do with the osmnx image), but that's a big change (not necessarily bad), requiring  re-thinking the whole architecture and workflow for users. (not sure that I'm up for that big a rewrite at this point... Perhaps something to think about for down the track)

Maybe I'm just not familiar with with the way things would work too see the obvious way to do this.

Any thoughts appreciated!

**Comment by carlhiggs** [comment]
Maybe this StackExchange post describes what I think we would want to do for using a Docker compose file to define environment: https://stackoverflow.com/a/64373702/4636357  ... perhaps this could work combining your example with this approach...  (our use case would be simpler as our Docker image isn't private)

**Comment by carlhiggs** [comment]
I think perhaps --- given we have tested this on Linux and Windows, and have no reason to expect issues on MacOS (previously worked there), on this occasion I will merge this, but created a new issue (#258) to capture the great idea to move more towards having a CI/CD workflow

**Pull request merged**
