### PR TITLE
fix paths

### PR DESCRIPTION
**Pull request by gboeing**
Currently if you're in bash in the `process` folder and run the documented command `python sv_sp.py odense.json true` you get the following error:

```
Failed to read json file.
[Errno 2] No such file or directory: '/home/jovyan/work/process/process/./configuration/odense.json'
Traceback (most recent call last):
  File "sv_sp.py", line 38, in <module>
    print('Start to process city: {}'.format(config["study_region"]))
NameError: name 'config' is not defined
```

The way the script assembles the path is broken, resulting in the nonexistent directory above.

### CODE REVIEW

**Comment by gboeing** [comment]
After fixing the path assembly in 3a683bc, another error appears:

```
Start to process city: odense
Start to reproject network
Traceback (most recent call last):
  File "sv_sp.py", line 43, in <module>
    G_proj = sss.readGraphml(graphmlProj_path, config)
  File "/home/jovyan/work/process/sv_setup_sp.py", line 279, in readGraphml
    graphml_path = os.path.join(dirname, config["folder"],
NameError: name 'dirname' is not defined
```

Because [this line](https://github.com/gboeing/global-indicators/blob/a826d5e132ef97e0bc36e4060832897c87738b48/process/sv_setup_sp.py#L279) references a `dirname` variable that is not defined anywhere.

**Comment by gboeing** [comment]
After fixing the `dirname` definition in 2949b56, another error appears:

```
Start to process city: odense
Start to reproject network
Traceback (most recent call last):
  File "sv_sp.py", line 43, in <module>
    G_proj = sss.readGraphml(graphmlProj_path, config)
  File "/home/jovyan/work/process/sv_setup_sp.py", line 285, in readGraphml
    G = ox.load_graphml(graphml_path)
  File "/opt/conda/lib/python3.7/site-packages/osmnx/save_load.py", line 333, in load_graphml
    G = nx.MultiDiGraph(nx.read_graphml(path, node_type=node_type))
  File "</opt/conda/lib/python3.7/site-packages/decorator.py:decorator-gen-660>", line 2, in read_graphml
  File "/opt/conda/lib/python3.7/site-packages/networkx/utils/decorators.py", line 214, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/process/./data/odense_dk_2019_10000m_pedestrian_osm_20190902.graphml'
```

Part of this is because I do not have that graphml file locally. But even if I did, that path wouldn't work. It's being assembled like:

```
graphml_path = os.path.join(dirname, config["folder"], config["graphmlName"])
```

But `config["folder"]` is being defined in `odense.json` like:

```
"folder": "./data"
```

Hence, extra `./` is ending up in the path.

**Comment by gboeing** [comment]
@carlhiggs @shiqin-liu can you take a look at this PR to confirm the issue existed for you as well and give any thoughts on this fix?

**Comment by shiqin-liu** [comment]
> @carlhiggs @shiqin-liu can you take a look at this PR to confirm the issue existed for you as well and give any thoughts on this fix?

I also encounter the same filepath error when running the scripts, but have not sorted out a fix yet. I will review the scripts more carefully and will update if I find the fix

**Comment by gboeing** [comment]
@shiqin-liu this PR should fix it once merged.

Also note I'm updating the docker image in #9

**Pull request merged**
