### PR TITLE
Jupyter Lab and Software set up on GitHub adjustments from issue #375

### PR DESCRIPTION
**Pull request by dapugacheva**
- Add the `fill_color` and `fill_opacity` parameters to the choropleth function.
- Add instructions on how to exit the software to the README file after the description of the Compare function and before.
- Correct text errors for the file path in the Sensitivity Analysis stage.

### CODE REVIEW

**Comment by carlhiggs** [comment]
Hi @dapugacheva ,

This looks good -- nice idea to add flexibility for users to optionally change the colour scheme.

A couple of suggestions:

1. provide a default `fill_colour` in addition to `fill_opacity` in the `plot_choropleth_map()` function so that those who don't want to worry about these parameters or don't know the colour strings can still get a map.  May as well add in line_opacity too, in case someone wants to edit it also.  But nice to provide defaults, so they can get a quick and easy map too.
```
    fill_color:str='YlGn',
    fill_opacity:float=0.7,
    line_opacity=0.1,
```

2. Regarding the exit blurb, nice idea to detail this.  I believe this bit "_or type `exit` in the terminal before closing the web app browser window_" won't work; at least, it doesn't on my computer, so I think it could be removed.  I don't think that we need to say "_Do not just close your browser tab or terminal window without stopping the web application or Jupyter first._".  Telling to people to exit when they are done is sufficient; so the first couple of sentences are great.

**Comment by carlhiggs** [comment]
Another thing I wonder is, perhaps in the example notebook, some users will be excited that they can change colours.  But others could be put off by the added complexity (a lot of our users are completely new to Python, so might not get the meaning of the options or the YlGn is yellow-green etc).  Another option could be, first do a basic map, so people know the basic command and that they don't have to add anything extra --- and then show how additional parameters can optionally be used to provide additional styling (maybe link to to the matplotlib colour maps https://matplotlib.org/stable/users/explain/colors/colormaps.html#classes-of-colormaps ).  What do you think?

**Comment by dapugacheva** [comment]
Hi @carlhiggs,

Thank you for your review! I added the default parameters for `fill_color`, `fill_opacity`, `line_opacity`. I think if `line_opacity` is added as a customized parameter, other parameters for line graphics like `line_color`, `line_weight` should be also included. However, it will make the code cell longer or might seem unnecessary yet nice.

The phrase _"Do not just close your browser tab or terminal window without stopping the web application or Jupyter first."_ intends to warn users to exit the app properly otherwise it will not run unless the docker's fully stopped and started again.

I think it's a great idea to add a quote explaining additional parameters with a link to the matplotlib colors. The default set parameters for graphics will ease the complexity for those who the new to Python. 

Let me know what you think and I can merge these changes to [global-healthy-liveable-cities:update-packages-and-methods-for-2024](https://github.com/global-healthy-liveable-cities/global-indicators/tree/update-packages-and-methods-for-2024).

**Comment by carlhiggs** [comment]
Hi @dapugacheva,

Thanks for those changes --- good point about adding other options (that could be endless).  In retrospect, perhaps another useful approach could have been allowing some sort of optional *args that could be passed on the sub-function, ultimately to Leaflet.  That probably would be a better way to implement things in the future, allowing users to engage directly with the options of the underlying function while not pre-empting usage of those parameters (except perhaps as defaults).  I also think it may be too much to worry about that now.  

Regarding the 'do not close' bit; I would feel better if that sentence were omitted.  I don't quite understand where you say 'it will not run unless the docker's fully stopped and started again'.  That's not my experience and surprises me; I usually exit in this way and don't have to restart the Docker container.  However, I do know to use "Ctrl+C" (or cmd+c presumably on an Apple device?) to interupt the Jupyter or NiceGUI server (or other long running processes).  Perhaps that would be the more useful bit of information to share, e.g.

> If you close a browser window with the Jupyter Lab or GHSCI app still running, the underlying server process running these may be interrupted by pressing `Control+C` or `Command+C` at the command prompt, depending on your operating system.

Could that work instead?  I guess it lets people know that nothing particularly bad will happen if they do close a window inadvertently, and there are other ways to do things.

If you're happy with that change and have tested out the functionality of the choropleth function and options yourself (or would like to write a unit test to do so - see [here](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/tests/tests.py); most welcome, if you would like to!), then I'm happy for it to be merged in.  Thanks!

**Comment by dapugacheva** [comment]
Hi @carlhiggs 

The choropleth function has been edited as discussed. I've tested it out, everything worked well. I also noted the possibility of changing graphic parameters (fill_color, etc) and linked the matplotlib colors palette.  

I eliminated the warning message replacing it with your quote. The `Control+C` shortcut works the same on the Mac. 

If you are okay with these last commits, I guess they are ready to be merged in.

**Review by carlhiggs — APPROVED** [review]
Thanks @dapugacheva, looks good!

**Comment by carlhiggs** [comment]
@dapugacheva I just merged these in as discussed.  Perhaps before we merge into the main branch we can wait for a few more of the planned amendments and then review whether instructions on the accompanying website etc need updating to reflect the changes.  Thanks!

**Pull request merged**
