### PR TITLE
gtfs headway analysis

### PR DESCRIPTION
**Pull request by shiqin-liu**
I have added our gtfs headway folder into the pre-process folder. I did some cleaning and update the documentation to reflect our current analysis. 

I can run the analysis for all other cities with the data. Let me know if you have any suggestion for improvement. 

I also noticed that our GTFS data in our Cloudstor are missing for some study regions when I downloaded them to test, like Chennai, HongKong, Phoenix, Seattle, Baltimore, Hanoi, Valencia, Mexico City, Befast (I believe these cities suppose to have the data? but their folder is empty...). 

I couldn't locate those data on my end. @carlhiggs Do you have copies of those data somewhere?  Also could you check if this workflow fit into your general pre-process branch (maybe after this is merged?). Thanks!!

### CODE REVIEW

**Comment by carlhiggs** [comment]
> I also noticed that our GTFS data in our Cloudstor are missing for some study regions when I downloaded them to test, like Chennai, HongKong, Phoenix, Seattle, Baltimore, Hanoi, Valencia, Mexico City, Befast (I believe these cities suppose to have the data? but their folder is empty...).
> 
> I couldn't locate those data on my end. @carlhiggs Do you have copies of those data somewhere? Also could you check if this workflow fit into your general pre-process branch (maybe after this is merged?). Thanks!!

Hi @shiqin-liu ; thanks for picking up on this --- the perils of working from home, when uploading large amounts of data to cloudstor i get timeouts.  I think I remember having issues with this at the time.  I'm re-attempting upload for those remaining cities' data now.  Hopefully this should all be uploaded when you are back online. 

Happy to have a go -- I'll aim to look at this tomorrow (Thurs AEST),

Update: the GTFS files should all be there on CloudStor now I believe (folder size summaries which were 0kb, now have substance in them -- so looks all good; as per snippet below):
image

**Comment by shiqin-liu** [comment]
I see. Thanks for uploading those, Carl! It seems there is a feed still missing under Chennai gtfs folder, that is a subfolder named `chennai-rail-gtfs-master`.  I got an error when running the code indicating that we don't have files in that folder when it gets to Chennai.

@carlhiggs Let me know if I should merge this into the main first, so you can fetch and test. Thanks!

**Comment by carlhiggs** [comment]
Hi @shiqin-liu -- ah yup, that's the issue with timeouts uploading to Cloudstor again; unfortunately it doesn't alert when things don't fully upload (it seems to have issues when there are many files in nested folders).  Mostly CloudStor works quite well (for Australian universities upload/download is very fast); but connection working from home is less reliable.  So apologies -- also looks like some of the Lisbon and Barcelona subfolders were missing too.  I have set these uploading again along with the Chennai one.  Some are completed, but despite small overall file size, but upload is slow from my computer and there are still repeated drop outs -- so I am  still attempting to get the Lisbon subfolders to upload to completion.  I will keep checking in, but because it doesn't alert to an error to say 'the upload was incomplete' its quite hard given all the folders and subfolders to verify completeness.  In retrospect, zipping everything up would have  been a good solution; on the other hand though, it is nice to be able to look at the folder contents online without extracting the full archive.  I guess the rationale for not zipping it all up is that, by downloading the 'Global Indicators -Data' folder and locating the contents in 'process\data' you have everything needed as inputs without further need for extraction.  But increased risk of incomplete upload transaction is apparently a real pain with this approach.  Hopefully everything you need is there when you next get a chance to look.

**Comment by shiqin-liu** [comment]
@carlhiggs 

Here are a list of cities I found having some missing files:
odense - missing trip.txt, 
auckland - missing stop.txt, 
bern-missing stop.txt, 
cologne -missing stop.txt
barcelona - AMB and TMB feeds missing a few files
lisbon - missing stop.txt (gtfs_portugal_lisbon_carris_20111015)


Thank you for checking! I will merge this PR for now, so that we can both test it when you get the Bangkok data ready.

**Comment by carlhiggs** [comment]
Thanks @shiqin-liu, I've just uploaded these (multiple missing files for most of these feeds sorry) along with the feed for Bangkok; I'll aim to have a go at updating the configuration script today to include Bangkok, and will look to running the analyses Monday next week.

**Pull request merged**
