### PR TITLE
fix links post repo move

### PR DESCRIPTION
**Pull request by gboeing**
Fix readme links pointing to old organization name.

### CODE REVIEW

**Comment by gboeing** [comment]
@carlhiggs CI tests are failing because it cannot log into docker hub. Did those secrets get migrated over with the repo?

**Comment by carlhiggs** [comment]
Thanks @gboeing ; I'll check it out later today --- think I set it up for the version I forked previously, but then after deleting that version I don't think I've added back in.  Will get to adding them back in a couple of hours.  Thanks for this pr and the prompt!

**Comment by carlhiggs** [comment]
Hi @gboeing ; its a bit of a strange one --- the repo secrets for for username and access token to Dockerhub for github actions actually did transfer.  I thought, perhaps I have to update them for them to work at new repo, and I just did this, but its still not working.  Something else odd might be going on, but at the moment, I'm not sure what.

Others have reported similar things, including recently (https://github.com/docker/login-action/issues/29).  I'll look through these threads and see if I can find any tips for resolving.

**Comment by carlhiggs** [comment]
Ah... I think I've found the answer --- but perhaps not the ideal solution:

https://github.com/yukihiko-shinoda/dockerfile-gatsby/pull/7#issuecomment-1902493017

> Turned out that pull request authors need to prepare Docker Hub account and set its account id and password into their forked repository:
> https://github.com/docker/login-action/issues/29#issuecomment-731206108

> We can change its setting to use secrets in original repository, however, it requires manual approval process and update GitHub Actions workflow comprexly:
> [Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests | GitHub Security Lab]>(https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Maybe the relevant bit, from the issue linked above, is
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-encrypted-secrets-in-a-workflow

Not exactly sure how best to resolve this, but perhaps one option suggested in the quoted post above is, perhaps you could create a repo secret username and personal access token login in your forked repository for your own Dockerhub account --- perhaps then it will use that?  

It sounds like the issue is that for security reasons, for a forked repo like the one you're using Github limits the access privileges to secrets in workflows triggered by that fork PR.  Probably sensible; fingers crossed some work around like the above works.  Let me know how it goes, or if you think there's a better way of dealing with it!

----

Edit: Another quick and easy option is, we just make the edits you made to your readme directly in the one in this repo.  I'm pretty sure if the changes are made within this repository and not a fork they should merge without the token issue.  Having said that, I expect we merged from forks of Daria and Ruoyu previously, so not why we didn't experience this issue then.  Anyway --- happy to proceed however you like with this; keen to hear your thoughts.

**Comment by carlhiggs** [comment]
@gboeing I'm going to merge this as its just changes to readme; the docker secrets transferred, and as per links in last post I made, I think its an issue with how Google allows forks of repositories to launch actions using secrets.

**Comment by gboeing** [comment]
Great, thanks.

**Pull request merged**
