### PR TITLE
added script to generate hexagon bins

### PR DESCRIPTION
**Pull request by DRosasMoctezuma**
The following script was adapted utilizing the Belfast city boundary; it is a preliminary version that will help our research. The original script was created by Navaneeth Mohan, using the city of Toronto as the study area. Please make suggestions as to the elements that should be changed or removed.

### CODE REVIEW

**Comment by gboeing** [comment]
> Please make suggestions as to the elements that should be changed or removed.

@DRosasMoctezuma is it ready for commenting now, or have you not yet finished the changes to be done following up on our Monday call?

**Comment by DRosasMoctezuma** [comment]
@gboeing The current version is from our Monday call; I added additional comments to the file. Other team members can make suggestions to this version as I will make revisions this week before Friday morning.

**Comment by gboeing** [comment]
Hi @DRosasMoctezuma is this PR ready to merge?

Can you add your to-do list items regarding this task from Monday's call to this PR as a comment, and just note the status of each?

**Comment by DRosasMoctezuma** [comment]
@gboeing Completed To-do list items::
- Convert script into single function 
- Generalized implementation to be able to run with gpkg from any city. 
- Make sure projection is based on gpkg (urban_study_region layer), meter based projection. 
- Hexagon bins - diameter = 500 meters. 
- return hexagon grid (hex_grid)

Currently researching how to determine if hexagon bins contain destination points.

**Comment by gboeing** [comment]
Thanks, I'll hold off on merging for now in that case.

**Comment by DRosasMoctezuma** [comment]
@gboeing  The output of the function would be a DataFrame containing the hexagon ID and points related information which can be written to a  csv file.

The following commands can be run to execute the functions of the script and generate the csv file:
_# Load necessary data (Example: Sao Paulo)_
study_area, gdf_official_destinations, gdf_osm_destinations = load_data('sao_paulo_br_2019_1600m_buffer.gpkg', 'SP_Freshfood_merged.shp')
_# Construct hexagon layer_
hex_grid, hex_grid_clipped = hex_plot('sao_paulo_br_2019_1600m_buffer.gpkg', gdf_osm_destinations, gdf_official_destinations)
_# Determine points present in hexagon layer_
result_df = determine_points_in_hexagon_bin(hex_grid_clipped, gdf_osm_destinations, gdf_official_destinations)
_# Write resulting data frame to csv_
result_df.to_csv("Hexagon_Points.csv", index=False)

**Comment by DRosasMoctezuma** [comment]
@gboeing Three additional columns have been added to the output csv file: Hex OSM Percentage, Hex Official Percentage, and Weight.

**Comment by DRosasMoctezuma** [comment]
Opened a new pull request: Function to generate hexagon bins and return weight indicators #72

**Pull request closed without merging**
