### PR TITLE
Update the findings for pois

### PR DESCRIPTION
**Pull request by thuanguy**
@gboeing

### CODE REVIEW

**Comment by gboeing** [comment]
@thuanguy you need to merge in all the new commits to the master branch to your local branch before we can merge this PR: `git pull upstream master`

You will have conflicts you'll need to resolve (remember, this normally should be done *before* doing any work or making any changes to prevent conflicts).

**Comment by thuanguy** [comment]
@gboeing I tried pull upstream but got an error saying the merge will overwrite my local changes. However, those local changes are those that I want to update. The conflicting files are those that I want to update in the master branch. How do I resolve these conflicts?

**Comment by gboeing** [comment]
@thuanguy see here at the bottom of this PR where it says "this branch has conflicts"... try those instructions about the command line.

**Comment by thuanguy** [comment]
@gboeing It seems to me that once the files have been merged into the master branch, I can't simply update them and merge them again since it will create conflicts right?

**Comment by gboeing** [comment]
You can merge commits into master, and then update those files and merge them again. The problem is that you didn't run `git pull upstream master` before making your latest changes, so you were editing old versions of the files (I edited them late last week). That's causing the conflict now that you're trying to merge in new updates and outdated stuff.

**Comment by thuanguy** [comment]
Got it. I have made a new PR.

**Pull request closed without merging**
