### PR TITLE
Update full-distance-fix with consistent field names

### PR DESCRIPTION
**Pull request by shiqin-liu**
This PR updates:

- the sample point indicators field names in setup_config.py and aggr.py so that they are consistent across the workflow.  

- update the full nodes functions so that it produces distance measures, then run convert to binary measures as a separate step. 

I test the workflow using Vic and Olomouc, both sample point and aggregation scripts are run successfully.

**Before merging into the upstream, there is a minor issue:**
Whenever coverting the origional node subgraph to gdf:
```
# convert subgraph into edge GeoDataFrame
subgraph_gdf = ox.graph_to_gdfs(subgraph_proj,
                                nodes=False,
                                edges=True,
                                node_geometry=False,
                                fill_edge_geometry=True)
```
It gives the warning message: 
```
/opt/conda/lib/python3.7/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
```
So we have 14087 nodes for Vic, when running the sp.py in the terminal, it shows this warning message 14087 times. But it does not seem to affect the workflow and the results.

Is there something that I should be aware of with this message? Anything we should do to address this?

### CODE REVIEW

**Comment by gboeing** [comment]
@shiqin-liu yes we should update all of our CRS definitions as that warning suggests. The old style is not compatible with future versions of the proj library.

**Comment by shiqin-liu** [comment]
> @shiqin-liu yes we should update all of our CRS definitions as that warning suggests. The old style is not compatible with future versions of the proj library.

@gboeing any suggestion on how to make this update?

Our current CRS in config json for example is:
`  
    "to_crs": {
        "init": "epsg:7845"
    }`

I make the change to `"to_crs": "epsg:7845"`, but the warning does not seem to go away, is that's something related to the input data source?

**Comment by gboeing** [comment]
Yeah updating them like `"epsg:7845"` should fix it... if you still get warnings there are probably still some old-style "init" CRS definitions somewhere in the code or data.

**Comment by shiqin-liu** [comment]
Thanks! I guess it is something related to the data, but I will double-check the workflow to make sure.

**Comment by shiqin-liu** [comment]
I have posted the CRS format issue in #58.  I think this should be ready to be merged into the master, if @gboeing and @carlhiggs you both think this looks OK.

**Comment by gboeing** [comment]
@shiqin-liu sounds good. If we have all the CRS's in our codebase here formatted correctly, then we should be ready to merge. If I don't hear otherwise from @carlhiggs I can do the merge tomorrow.

**Pull request merged**
