### PR TITLE
Pull request 

### PR DESCRIPTION
**Pull request by carlhiggs**
Hi team, 

Would you mind checking and approving this pull request?  There were two files causing crashes due to subtle issues (I will later work on tests to ensure this doesn't happen again):

- process/configuration/templates/osm_destination_definitions.csv had ANSI coding instead of UTF-8; I missed updating the template file apparently (only my local copy)
- global-indicators.sh had windows line endings (\r\n) instead of unix-style (\n); while my local version has unix style when its commited via Git it converts these to windows (I should change my commit settings).  Maybe a github action could check for that post-commit, as a pre-commit test probably wouldn't pick it up.  This file doesn't change often, but it was amended in the recent enhancements branch update that was merged, and that's how it slipped through.

So I directly uploaded and verified that those have been fixed on this 'testing' branch.

If okay with you, I'll merge it into main.   This is a pretty important fix as each of these issues causes a problem, so perhaps just one approval I think should be enough.  I've downloaded the files directly to confirm that the new versions have the respective issues addressed.

Later today I mean to create some pre-commit (and possibly post-commit) tests to catch this kind of issue in future.

Thank you!

Carl

### CODE REVIEW

**Comment by carlhiggs** [comment]
This pull request address #181 and #183

**Comment by gboeing** [comment]
FYI there is a `mixed-line-ending` pre-commit hook.

**Comment by carlhiggs** [comment]
> FYI there is a `mixed-line-ending` pre-commit hook.

Thanks @gboeing, [mixed-line-ending](mixed-line-ending) sounds promising... although just reading it's guide,
image

sounds like my particular current system (which I think is the problem) would still auto-convert to LF subsequent to the hook.

I can change my system (probably should), but will be good to have something else to watch this file for that (its slipped through a few times now).   

Maybe a [.gitattributes](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings) file could be a good option to ensure for this particular repository LF line endings are enforced?

**Comment by carlhiggs** [comment]
I think if I add a .gitattributes with the following, at least .sh files will be correctly handled; they are probably the only ones where this matters:

```
# Declare files that will always have LF line endings on checkout.
*.sh text eol=lf
```

... I'll give it a go

**Comment by carlhiggs** [comment]
Hi @global-healthy-liveable-cities/software-spatial  & @gboeing  (apologies I know its late where you are Geoff!), 
Would you be okay if I merged this into main?  It addresses the three bugs I am aware of.  Currently each of those will cause a failure for the process to run on new installs.

As discussed above, in the medium term I will work on introducing tests to mitigate risk of introducing bugs for further releases (I've created a new file tests/tests.py where I've made a start; that can be expanded on).

In the short term, after this is merged into main, I will update the enhancements branch (which has an active pull request that is being worked on) with these changes and attempt to address the comments from that review.

But as for this pull request -- I think its good to go; I have checked that the 3 specific bugs are addressed, and run the process in full for Ghent (v3) successfully.

**Comment by gboeing** [comment]
Looks good.

**Comment by carlhiggs** [comment]
Thanks @gboeing  - i'll merge this one in, and then update the 'enhancements' with these changes before continuing on with that (less of a priority).  Its good that this has broken the ice on introducing testing to the project (#182).

**Pull request merged**
