### PR TITLE
process code cleanup

### PR DESCRIPTION
**Pull request by gboeing**
@shiqin-liu I'm doing some code cleanup in the `process` folder prior to you testing it this week. This will make the code format and style consistent throughout the project, in line with #75.

### CODE REVIEW

**Comment by gboeing** [comment]
@shiqin-liu this is ready for your review. If you approve these changes I will merge them into master. Note that this is mostly code cleanup and formatting for consistency across the project. However do note the one substantive change in 3eebb35e709b5373e39d3671cc147a633627a960 where I add new exception handling, because otherwise we were hitting an error (with the new version of OSMnx in the docker image) when a subgraph occasionally lacked edges.

I've tested it on Odense and Olomouc.

cc @carlhiggs in case you'd like to place another pair of eyeballs on this

**Comment by gboeing** [comment]
@shiqin-liu one more note: it looks like the readme in the process folder is out of date and does not account for your changes to config json file creation via the script.

**Comment by gboeing** [comment]
Also e3667b2 adds a fix for the bug documented in #77

**Comment by shiqin-liu** [comment]
Thanks, Geoff! These look good to me. I will update the process readme when re-testing this week.

**Review by shiqin-liu — APPROVED** [review]

**Pull request merged**
