### PR TITLE
Add GTFS frequent stop analysis folder

### PR DESCRIPTION
**Pull request by shiqin-liu**
The core idea of current frequency analysis is adopted from the average headway approach that Carl has been working on for Australian cities, and generalize to work in the global context. Updates are to be expected as required.

TODOs (updated):

- [x]  need to think about ways to refactor the code to work with cities with more than one transit feed
> - bring in frequencies.txt (urban access doesn't do this it seems)
> - simplified some of the datetime parsing (allowed some things to be written more concisely)
> - added direction_id, and ensured there were no nulls (to allow grouping over this, avoid logic loop - less code)
> - comment out the 'representative week' code -- this code caused Mexico City trains not to be processed. We average over dates anyway, so I think this is fair.
> - weight hours in frequency.txt (for taking weighted average of headway for hours within analysis window; hours outside analysis window are weighted zero --- but before then, any zero weight rows are dropped anyway)
> - if there are stops with valid trip frequencies and positive weight defined, these will be used; any other stops are defined using stop_times if possible
> - Updated GTFS configuration with new 'validation':False parameter.  It happens to be set False for all layers, however the main impact is only observable for Odense and Bern.  By setting validation to False, the code now creates a 'cleaned' version of stop_times with stops restricted to those within the limits of the current city's bounding box.

- [x] need to discuss transit mode specifications used for the global context
> - amended modes to reflect GTFS standard route types by default (modified where exceptions occur)

- [x] need to validate correct school terms for each study region

- [ ] clean and test the updated code with available GTFS cities, further changes may be expected to make

### CODE REVIEW

**Comment by shiqin-liu** [comment]
@gboeing could you update the docker with UrbanAccess package if you get a chance? I use some UrbanAccess functions to load the GTFS data in this workflow. It seems like now I need to reinstall the package every time I rerun the docker container. 

Thanks!

**Comment by gboeing** [comment]
> could you update the docker with UrbanAccess package if you get a chance?

@shiqin-liu yes I can. But I might suggest we see if anything else needs to change in the docker image, so we update everything at once. For instance, I'm planning to release the new version of OSMnx in about 10 days: should we wait for that to incorporate the latest in the image? Any other changes to make?

cc @carlhiggs

**Comment by shiqin-liu** [comment]
Thanks, @gboeing I agree it is good to wait to incorporate more updates. On my end, I cannot think of other changes other than UrbanAccess for now, but that's is not urgent. Excited to know about the new version OSMnx release, should we expect any significant changes in our workflow if incorporating this new version (other than the POIs and clean intersections we know of)?

**Comment by gboeing** [comment]
> Excited to know about the new version OSMnx release, should we expect any significant changes in our workflow if incorporating this new version (other than the POIs and clean intersections we know of)?

@shiqin-liu you can see the draft [change log](https://github.com/gboeing/osmnx/blob/master/CHANGELOG.md) for what's new in the release as currently planned. It's a major refactor, but *most* of it should be seamless for the end user. A couple function names have changed, and file save/load filepath parameters have changed. You can see the proposed release functionality in the [latest docs](https://osmnx.readthedocs.io/en/latest/).

**Comment by gboeing** [comment]
Per my action item, I spent some time this morning updating and rebuilding the [docker image](https://hub.docker.com/r/gboeing/global-indicators/tags?page=1&ordering=last_updated). It is available now to pull via the `latest` tag. See commit 0001e71b0a1a15c8f8bc088a6b777aff40cc8132 for changes.

cc @carlhiggs @nicholas-david @duelran @DRosasMoctezuma

**Comment by gboeing** [comment]
@shiqin-liu see comment: https://github.com/shiqin-liu/global-indicators/pull/7#issuecomment-682067842

It looks like this is an issue with this PR's diff.

**Comment by shiqin-liu** [comment]
Thanks, Geoff. I must have missed the notification for the https://github.com/shiqin-liu/global-indicators/pull/7. I have reviewed and merged the updated PR [Carlhiggs gtfs frequency patch 1](https://github.com/shiqin-liu/global-indicators/pull/8) by Carl. They look good to me on my branch. Is there still a problem with this PR's diff? should I close this for now?

**Comment by gboeing** [comment]
@shiqin-liu yes, see the diff at the top of the PR's page: `+2,444,647 −0 `

It's adding millions of lines to the repo because all the data files are included in the commit history.

**Comment by shiqin-liu** [comment]
OK, I see... I will close this for now then, I am pretty sure I ignore all the .txt data file, but I will check on my branch again, and make sure all are good before making a new PR.

**Comment by gboeing** [comment]
Note that you'll need to remove it from the commit history, not just ignore it, because it's already in there.

**Pull request closed without merging**
