### PR TITLE
Add documentation folder

### PR DESCRIPTION
**Pull request by nicholas-david**
This pr adds documentation for the whole project.

To-do list:
 - [x] Create an organized way to retrieve data
 - [ ] Document what the data is, its units, where it comes from, etc.
 - [x] Document Validation Folder
 - [x] Explain Validation process and types
 - [ ] Define Key terms for the project

### CODE REVIEW

**Comment by nicholas-david** [comment]
- [ ] abc

**Comment by gboeing** [comment]
@nicholas-david Thu's validation work has been wrapped up for the semester and is in the `/validation` folder now. Can be included in your documentation consolidation.

**Comment by nicholas-david** [comment]
@gboeing is there a way to make lettered lists in markdown? For example:
a. first thing
b. second thing
Thanks

**Comment by gboeing** [comment]
> is there a way to make lettered lists in markdown

@nicholas-david markdown rendering automatically picks 1, 2, 3, etc for a numbered list, but you can do nested numbered lists like this (note each sublist is indented 4 spaces):

```
1. abc
    1. xyz
    1. uvw
        1. jkl
        1. mno
    1. rst
1. def
1. ghi
```

And it will render like this:

1. abc
    1. xyz
    1. uvw
        1. jkl
        1. mno
    1. rst
1. def
1. ghi

**Comment by gboeing** [comment]
@nicholas-david see validation updates from Thu last night in #41 (merged into master now).

**Pull request merged**
